@ECHO OFF
echo Cleaning working directory...
del ImageTweak.xpi >nul 2>nul
del ImageTweak.zip >nul 2>nul
echo Creating XPI...
"%PROGRAMFILES%\7-Zip\7z" a -x!.git* -x!*.bat -mx9 -tzip ImageTweak.xpi * >nul 2>nul
echo Cleaning up...
echo All done!